name: Release version

on:
    push:
        branches:
            - main
            - 'push-action/**'

jobs:
    release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: ./blocks/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Build project
              run: make

            - name: Commit built blocks
              uses: EndBug/add-and-commit@v9
              with:
                  add: 'scripts/build'
                  message: 'chore(build): build scripts for release [skip ci]'
                  default_author: github_actions
                  push: false

            - name: Conventional Changelog Action
              uses: TriPSs/conventional-changelog-action@v3
              with:
                  github-token: ${{ secrets.MASTER_PAT }}
                  version-file: './package.json'
                  fallback-version: 3.0.0
                  git-push: false
                  pre-commit: './versionSync.mjs'

            - name: Push to protected branch
              uses: CasperWA/push-protected@v2
              with:
                  token: ${{ secrets.MASTER_PAT }}
                  branch: main
                  tags: true
                  unprotect_reviews: true
